//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0202_Practixhka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int ID { get; set; }
        public string material_name { get; set; }
        public Nullable<int> material_type { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> quantity_in_warehouse { get; set; }
        public Nullable<double> minimal_quantity { get; set; }
        public Nullable<int> quantity_in_pack { get; set; }
        public Nullable<int> unit_of_measurement { get; set; }
    
        public virtual Material_type Material_type1 { get; set; }
        public virtual Units_of_measurement Units_of_measurement { get; set; }
    }
}
