//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0202_Practixhka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_products_request
    {
        public int ID { get; set; }
        public Nullable<int> prodcut { get; set; }
        public Nullable<int> partner { get; set; }
        public Nullable<int> product_quantity { get; set; }
    
        public virtual Partner Partner1 { get; set; }
        public virtual Products_import Products_import { get; set; }
    }
}
