//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0202_Practixhka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.Partner_products_request = new HashSet<Partner_products_request>();
        }
    
        public int ID { get; set; }
        public Nullable<int> partner_type { get; set; }
        public string partner_name { get; set; }
        public string director_surname { get; set; }
        public string director_name { get; set; }
        public string director_patronymic { get; set; }
        public string partner_email { get; set; }
        public string phone { get; set; }
        public string partner_adress { get; set; }
        public Nullable<double> INN { get; set; }
        public Nullable<int> rating { get; set; }
    
        public virtual Partners_types Partners_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_products_request> Partner_products_request { get; set; }
    }
}
