//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0202_Practixhka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_import
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products_import()
        {
            this.Partner_products_request = new HashSet<Partner_products_request>();
        }
    
        public int ID { get; set; }
        public Nullable<int> product_type { get; set; }
        public string product_name { get; set; }
        public Nullable<double> article { get; set; }
        public Nullable<double> patner_minimal_price { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Product_types Product_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_products_request> Partner_products_request { get; set; }
    }
}
